### ISSUE TITLE
Find name x that is not in the arguments

### ISSUE THREAD

**Issue by Rizhiy** [onnx/onnx-mxnet#13]
If I side-step the error in #12 (by reducing input size), I get another error of the type `Value Error: Find name "param_x" that is not in the arguments`. I checked the loaded params and they do contain `param_x` as a key.

Here is the full stack trace:
```
Traceback (most recent call last):
  File "load.py", line 16, in <module>
    mod.set_params(arg_params=params, aux_params=None, allow_missing=True)
  File "/home/rizhiy/miniconda3/envs/mxnet-mkl/lib/python3.6/site-packages/mxnet/module/module.py", line 356, in set_params
    self._exec_group.set_params(arg_params, aux_params, allow_extra=allow_extra)
  File "/home/rizhiy/miniconda3/envs/mxnet-mkl/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 371, in set_params
    exec_.copy_params_from(arg_params, aux_params, allow_extra_params=allow_extra)
  File "/home/rizhiy/miniconda3/envs/mxnet-mkl/lib/python3.6/site-packages/mxnet/executor.py", line 359, in copy_params_from
    raise ValueError('Find name \"%s\" that is not in the arguments' % name)
ValueError: Find name "param_3" that is not in the arguments
```
[Here is the model used](https://drive.google.com/open?id=1Ip87G-Cuh1HB7LDD2d674qmeDF-Ql8Sl)

And here is the code used to load generate the error:
```python
import onnx_mxnet

import numpy as np
import mxnet as mx

from collections import namedtuple

sym, params = onnx_mxnet.import_model('data/trained_models/model.onnx')

test_image = np.random.rand(1, 3, 224, 112)

mod = mx.mod.Module(symbol=sym, data_names=['input_0'], context=mx.cpu(), label_names=None)
mod.bind(for_training=False, data_shapes=[('input_0', test_image.shape)], label_shapes=None)
mod.set_params(arg_params=params, aux_params=None, allow_missing=True)
```

**Comment by Roshrini** [comment]
Can you try 
"mod.set_params(arg_params=params, aux_params=None, allow_missing=True, **allow_extra=True**)" once?

**Comment by Rizhiy** [comment]
That doesn't raise an error but, then my outputs are 30 orders of magnitude greater than in the original model.

**Comment by Rizhiy** [comment]
The problem seems to be that batch_norm expects `aux_params` for some of its weights, so we need to use
```python
mod.set_params(arg_params=params, aux_params=params, allow_missing=True, allow_extra=True)
```

**Comment by lupesko** [comment]
@Rizhiy I agree that `onnx_mxnet.import_model`should return `aux_params` as well.
MXNet uses `aux_params` to store params that are not learned during backprop.

@Roshrini can you please fix this issue, and make sure we have unit tests to cover BatchNorm?

**Comment by fengxinjie** [comment]
@Rizhiy I met the same problem, do you fix it?

**Comment by Rizhiy** [comment]
@fengxinjie I ended up folding BN into convolutions in PyTorch before exporting and it worked fine. Also has added the benefit of faster inference.

**Comment by fengxinjie** [comment]
@Rizhiy thanks very much,  when  I want to load two different models shared some variable name within two different python classes, this problem comes up, I donot know how to fix it.   And this never a problem for tensorflow.

**Comment by Rizhiy** [comment]
@fengxinjie Not completely sure what you mean, but it looks like you are trying to export a dynamic model from PyTorch. Unfortunately, ONNX doesn't support dynamic models currently.

**Comment by fengxinjie** [comment]
@Rizhiy sorry for my poor English, and thank for you reply.  What I mean is, when  I load checkpoint  c1  in Class A,  then l load another checkpoint c2 in class B,  this seems do not work when c1 and c2 share some variable names.  But you can  load all the checkpoints independently.    And  its never a problem for tensorflow, because you can load different checkpoint in different graphs.

**Comment by Rizhiy** [comment]
@fengxinjie I have never tried to do that, so I can't help you. Perhaps you need to create a separate issue describing in detail your problem.

**Comment by anirudhacharya** [comment]
@Rizhiy Try the above model with the latest mxnet master - https://github.com/apache/incubator-mxnet

The following code works with your model. The shape of the input in your code was (1, 3, 224, 112). I changed it to this (1, 3, 256, 128) and it works fine.

```python
import mxnet as mx
from mxnet.contrib import onnx as onnx_mxnet

import numpy as np

from collections import namedtuple

sym, arg, aux = mx.contrib.onnx.import_model('model.onnx')

test_image = np.random.rand(1, 3, 256, 128)

mod = mx.mod.Module(symbol=sym, data_names=['input_0'], context=mx.cpu(), label_names=None)
mod.bind(for_training=False, data_shapes=[('input_0', test_image.shape)], label_shapes=None)
mod.set_params(arg_params=arg, aux_params=aux, allow_missing=True)
```

Please reopen the issue if this problem persists.
