### ISSUE TITLE
UserWarning: Attribute axis is disabled in sym.broadcast_add

### ISSUE THREAD

**Issue by aaronmarkham** [onnx/onnx-mxnet#15]
When exporting squeezenet.onnx via mxnet-model-server.
[Issue started with mms](https://github.com/awslabs/mxnet-model-server/issues/275), but moving here since this specific warning is coming from onnx-mxnet.

It may or may not be a problem, but it would be nice to resolve warnings, or handle them in a way that doesn't alarm the user. Specifically, if this isn't a problem, then say so, otherwise I'm suspicious of my newly exported model.

```
/Library/Python/2.7/site-packages/onnx_mxnet-0.3.1-py2.7.egg/onnx_mxnet/common.py:97: UserWarning: Attribute axis is disabled in sym.broadcast_add
```

**Comment by Roshrini** [comment]
solved with #16
