### ISSUE TITLE
Operator Squeeze not implemented

### ISSUE THREAD

**Issue by oronanschel** [onnx/onnx-mxnet#17]
I’m trying to use the onnx_mxnet package to import an ONNX model to MXNet (python interface).
While doing so, I get the following error:
“NotImplementedError: Operator Squeeze not implemented”

The funny thing is that when I’m using the “onnx_caffe2” package to import the same model to Caffe2, it works.

**Comment by lupesko** [comment]
Hi Oron - thanks for submitting an issue.
What version of onnx-mxnet are you using? can you please install from source and try again?
(`git clone` the repo, then do `pip install .` )

If you still get an error, please share your model, import code, and the full error stack trace.

**Comment by oronanschel** [comment]
Hi!

I've reinstalled onnx-mxnet (using git clone + pip).
I've added the following code lines to the NVIDIA-flownet2 pytorch package to export a model to mxnet using onnx (https://github.com/NVIDIA/flownet2-pytorch):

f = open("./FlowNet2S.onnx", 'w')
torch.onnx.export(model, dummy_inputs, f, verbose=True)

The log show me that the following graph was saved:
graph(%1 : Float(1, 3, 2, 384, 1024)
      %2 : Float(64, 6, 7, 7)
      %3 : Float(64)
      %4 : Float(128, 64, 5, 5)
      %5 : Float(128)
      %6 : Float(256, 128, 5, 5)
      %7 : Float(256)
      %8 : Float(256, 256, 3, 3)
      %9 : Float(256)
      %10 : Float(512, 256, 3, 3)
      %11 : Float(512)
      %12 : Float(512, 512, 3, 3)
      %13 : Float(512)
      %14 : Float(512, 512, 3, 3)
      %15 : Float(512)
      %16 : Float(512, 512, 3, 3)
      %17 : Float(512)
      %18 : Float(1024, 512, 3, 3)
      %19 : Float(1024)
      %20 : Float(1024, 1024, 3, 3)
      %21 : Float(1024)
      %22 : Float(1024, 512, 4, 4)
      %23 : Float(512)
      %24 : Float(1026, 256, 4, 4)
      %25 : Float(256)
      %26 : Float(770, 128, 4, 4)
      %27 : Float(128)
      %28 : Float(386, 64, 4, 4)
      %29 : Float(64)
      %30 : Float(2, 1024, 3, 3)
      %31 : Float(2)
      %32 : Float(2, 1026, 3, 3)
      %33 : Float(2)
      %34 : Float(2, 770, 3, 3)
      %35 : Float(2)
      %36 : Float(2, 386, 3, 3)
      %37 : Float(2)
      %38 : Float(2, 194, 3, 3)
      %39 : Float(2)
      %40 : Float(2, 2, 4, 4)
      %41 : Float(2, 2, 4, 4)
      %42 : Float(2, 2, 4, 4)
      %43 : Float(2, 2, 4, 4)) {
  %62 : UNKNOWN_TYPE = Constant[value={255}](), uses = [%63.i1];
  %63 : Float(1, 3, 2, 384, 1024) = Div[broadcast=1](%1, %62), uses = [%64.i0, %66.i0];
  %64 : UNKNOWN_TYPE = Slice[axes=[0, 1, 2, 3, 4], ends=[1, 3, 1, 384, 1024], starts=[0, 0, 0, 0, 0]](%63), uses = [%65.i0];
  %65 : Float(1, 3!, 384, 1024) = Squeeze[axes=[2]](%64), uses = [%68.i0];
  %66 : UNKNOWN_TYPE = Slice[axes=[0, 1, 2, 3, 4], ends=[1, 3, 2, 384, 1024], starts=[0, 0, 1, 0, 0]](%63), uses = [%67.i0];
  %67 : Float(1, 3!, 384, 1024) = Squeeze[axes=[2]](%66), uses = [%68.i1];
  %68 : Float(1, 6, 384, 1024) = Concat[axis=1](%65, %67), uses = [%69.i0];
  %70 : UNKNOWN_TYPE = Conv[kernel_shape=[7, 7], strides=[2, 2], pads=[3, 3, 3, 3], dilations=[1, 1], group=1](%68, %2), uses = [[%71.i0]];
  %71 : Float(1, 64, 192, 512) = Add[broadcast=1, axis=1](%70, %3), uses = [%72.i0];
  %72 : Float(1, 64, 192, 512) = LeakyRelu[alpha=0.1](%71), uses = [%73.i0];
  %74 : UNKNOWN_TYPE = Conv[kernel_shape=[5, 5], strides=[2, 2], pads=[2, 2, 2, 2], dilations=[1, 1], group=1](%72, %4), uses = [[%75.i0]];
  %75 : Float(1, 128, 96, 256) = Add[broadcast=1, axis=1](%74, %5), uses = [%76.i0];
  %76 : Float(1, 128, 96, 256) = LeakyRelu[alpha=0.1](%75), uses = [%77.i0, %156.i0];
  %78 : UNKNOWN_TYPE = Conv[kernel_shape=[5, 5], strides=[2, 2], pads=[2, 2, 2, 2], dilations=[1, 1], group=1](%76, %6), uses = [[%79.i0]];
  %79 : Float(1, 256, 48, 128) = Add[broadcast=1, axis=1](%78, %7), uses = [%80.i0];
  %80 : Float(1, 256, 48, 128) = LeakyRelu[alpha=0.1](%79), uses = [%81.i0];
  %82 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%80, %8), uses = [[%83.i0]];
  %83 : Float(1, 256, 48, 128) = Add[broadcast=1, axis=1](%82, %9), uses = [%84.i0];
  %84 : Float(1, 256, 48, 128) = LeakyRelu[alpha=0.1](%83), uses = [%85.i0, %144.i0];
  %86 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%84, %10), uses = [[%87.i0]];
  %87 : Float(1, 512, 24, 64) = Add[broadcast=1, axis=1](%86, %11), uses = [%88.i0];
  %88 : Float(1, 512, 24, 64) = LeakyRelu[alpha=0.1](%87), uses = [%89.i0];
  %90 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%88, %12), uses = [[%91.i0]];
  %91 : Float(1, 512, 24, 64) = Add[broadcast=1, axis=1](%90, %13), uses = [%92.i0];
  %92 : Float(1, 512, 24, 64) = LeakyRelu[alpha=0.1](%91), uses = [%93.i0, %132.i0];
  %94 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%92, %14), uses = [[%95.i0]];
  %95 : Float(1, 512, 12, 32) = Add[broadcast=1, axis=1](%94, %15), uses = [%96.i0];
  %96 : Float(1, 512, 12, 32) = LeakyRelu[alpha=0.1](%95), uses = [%97.i0];
  %98 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%96, %16), uses = [[%99.i0]];
  %99 : Float(1, 512, 12, 32) = Add[broadcast=1, axis=1](%98, %17), uses = [%100.i0];
  %100 : Float(1, 512, 12, 32) = LeakyRelu[alpha=0.1](%99), uses = [%101.i0, %120.i0];
  %102 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%100, %18), uses = [[%103.i0]];
  %103 : Float(1, 1024, 6, 16) = Add[broadcast=1, axis=1](%102, %19), uses = [%104.i0];
  %104 : Float(1, 1024, 6, 16) = LeakyRelu[alpha=0.1](%103), uses = [%105.i0];
  %106 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%104, %20), uses = [[%107.i0]];
  %107 : Float(1, 1024, 6, 16) = Add[broadcast=1, axis=1](%106, %21), uses = [%108.i0];
  %108 : Float(1, 1024, 6, 16) = LeakyRelu[alpha=0.1](%107), uses = [%109.i0, %115.i0];
  %110 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%108, %30), uses = [[%111.i0]];
  %111 : Float(1, 2, 6, 16) = Add[broadcast=1, axis=1](%110, %31), uses = [%113.i0];
  %114 : UNKNOWN_TYPE = Constant[value= 0  0 [ CPUFloatTensor{2} ]](), uses = [%113.i2];
  %113 : Float(1, 2, 12, 32) = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%111, %40, %114), uses = [%120.i2];
  %116 : UNKNOWN_TYPE = Constant[value=<Tensor>](), uses = [%115.i2];
  %117 : UNKNOWN_TYPE = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%108, %22, %116), uses = [[%118.i0]];
  %118 : Float(1, 512, 12, 32) = Add[broadcast=1, axis=1](%117, %23), uses = [%119.i0];
  %119 : Float(1, 512, 12, 32) = LeakyRelu[alpha=0.1](%118), uses = [%120.i1];
  %120 : Float(1, 1026, 12, 32) = Concat[axis=1](%100, %119, %113), uses = [%121.i0, %127.i0];
  %122 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%120, %32), uses = [[%123.i0]];
  %123 : Float(1, 2, 12, 32) = Add[broadcast=1, axis=1](%122, %33), uses = [%125.i0];
  %126 : UNKNOWN_TYPE = Constant[value= 0  0 [ CPUFloatTensor{2} ]](), uses = [%125.i2];
  %125 : Float(1, 2, 24, 64) = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%123, %41, %126), uses = [%132.i2];
  %128 : UNKNOWN_TYPE = Constant[value=<Tensor>](), uses = [%127.i2];
  %129 : UNKNOWN_TYPE = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%120, %24, %128), uses = [[%130.i0]];
  %130 : Float(1, 256, 24, 64) = Add[broadcast=1, axis=1](%129, %25), uses = [%131.i0];
  %131 : Float(1, 256, 24, 64) = LeakyRelu[alpha=0.1](%130), uses = [%132.i1];
  %132 : Float(1, 770, 24, 64) = Concat[axis=1](%92, %131, %125), uses = [%133.i0, %139.i0];
  %134 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%132, %34), uses = [[%135.i0]];
  %135 : Float(1, 2, 24, 64) = Add[broadcast=1, axis=1](%134, %35), uses = [%137.i0];
  %138 : UNKNOWN_TYPE = Constant[value= 0  0 [ CPUFloatTensor{2} ]](), uses = [%137.i2];
  %137 : Float(1, 2, 48, 128) = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%135, %42, %138), uses = [%144.i2];
  %140 : UNKNOWN_TYPE = Constant[value=<Tensor>](), uses = [%139.i2];
  %141 : UNKNOWN_TYPE = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%132, %26, %140), uses = [[%142.i0]];
  %142 : Float(1, 128, 48, 128) = Add[broadcast=1, axis=1](%141, %27), uses = [%143.i0];
  %143 : Float(1, 128, 48, 128) = LeakyRelu[alpha=0.1](%142), uses = [%144.i1];
  %144 : Float(1, 386, 48, 128) = Concat[axis=1](%84, %143, %137), uses = [%145.i0, %151.i0];
  %146 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%144, %36), uses = [[%147.i0]];
  %147 : Float(1, 2, 48, 128) = Add[broadcast=1, axis=1](%146, %37), uses = [%149.i0];
  %150 : UNKNOWN_TYPE = Constant[value= 0  0 [ CPUFloatTensor{2} ]](), uses = [%149.i2];
  %149 : Float(1, 2, 96, 256) = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%147, %43, %150), uses = [%156.i2];
  %152 : UNKNOWN_TYPE = Constant[value=<Tensor>](), uses = [%151.i2];
  %153 : UNKNOWN_TYPE = ConvTranspose[kernel_shape=[4, 4], strides=[2, 2], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%144, %28, %152), uses = [[%154.i0]];
  %154 : Float(1, 64, 96, 256) = Add[broadcast=1, axis=1](%153, %29), uses = [%155.i0];
  %155 : Float(1, 64, 96, 256) = LeakyRelu[alpha=0.1](%154), uses = [%156.i1];
  %156 : Float(1, 194, 96, 256) = Concat[axis=1](%76, %155, %149), uses = [%157.i0];
  %158 : UNKNOWN_TYPE = Conv[kernel_shape=[3, 3], strides=[1, 1], pads=[1, 1, 1, 1], dilations=[1, 1], group=1](%156, %38), uses = [[%159.i0]];
  %159 : Float(1, 2, 96, 256) = Add[broadcast=1, axis=1](%158, %39), uses = [%0.i0];
  return (%159);
}



when I run the following line:
sym, params = onnx_mxnet.import_model('FlowNet2S.onnx')

I get this error message:
Traceback (most recent call last):
  File "pytorch_to_mxnet.py", line 40, in <module>
    sym, params = onnx_mxnet.import_model('FlowNet2S.onnx')
  File "/usr/local/lib/python2.7/dist-packages/onnx_mxnet/__init__.py", line 35, in import_model
    sym, params = graph.from_onnx(model_proto.graph)
  File "/usr/local/lib/python2.7/dist-packages/onnx_mxnet/import_onnx.py", line 115, in from_onnx
    new_op, mx_attr = _convert_operator(op_name, onnx_attr)
  File "/usr/local/lib/python2.7/dist-packages/onnx_mxnet/import_onnx.py", line 51, in _convert_operator
    raise NotImplementedError("Operator {} not implemented.".format(op_name))
NotImplementedError: Operator Squeeze not implemented.

**Comment by spidyDev** [comment]
"squeeze" operator support has been added to onnx-mxnet repo with PR:
https://github.com/onnx/onnx-mxnet/pull/23

**Comment by oronanschel** [comment]
Thanks spidy!
Now it works.

**Comment by zhanglanqing** [comment]
@oronanschel can you share your implementation of flownet2 with mxnet? thanks ;-)
