### ISSUE TITLE
No module named 'import_onnx'

### ISSUE THREAD

**Issue by ilkarman** [onnx/onnx-mxnet#2]
When I try:

`import onnx_mxnet`

I get the error:

> /anaconda/envs/py35/lib/python3.5/site-packages/onnx_mxnet-0.2-py3.5.egg/onnx_mxnet/__init__.py in <module>()
>      10 
>      11 # coding: utf-8
> ---> 12 from import_onnx import GraphProto
>      13 import onnx
>      14 
> 
> ImportError: No module named 'import_onnx'

I have the latest onnx install and can run onnx-caffe2 fine

**Comment by mitmul** [comment]
@ilkarman I think it's been fixed by #1

**Comment by ilkarman** [comment]
Yes it has, thank you! Silly didn't spot the dot :D

**Comment by kjchalup** [comment]
Hi,
I pip installed onnx_mxnet today (Dec 23rd) and get this same error. Has the fix been deployed?
