### ISSUE TITLE
ONNX Operator "MaxPool" Conversion Error - "Only 2d kernel supported"

### ISSUE THREAD

**Issue by HeliWang** [onnx/onnx-mxnet#26]
When converting "MaxPool" operator in ONNX to MxNet, onnx_mxnet throws an error for the graph line "MaxPool {'kernel_shape': (49,), 'pads': (0,), 'strides': (49,)} None None" with runtime exception "Only 2d kernel supported."

Seems to be a quick fix? Thanks

![maxpoool](https://user-images.githubusercontent.com/12112939/36490496-62a84d92-16f6-11e8-83db-44d256fe98b7.png)

**Comment by Roshrini** [comment]
@HeliWang Not a quick fix but will keep this as a feature request for next release.

@spidyDev @anirudhacharya Should we add multidimensional support for pooling, conv, deconv layers?

**Comment by anirudhacharya** [comment]
Yes I think we should add it in the next release.

**Comment by anirudhacharya** [comment]
@HeliWang check with the latests code https://github.com/apache/incubator-mxnet and reopen this issue if you still see a problem with the maxpool operator. The current code passes tests with Maxpool_1d, 2d and 3d.
