### ISSUE TITLE
Implement Backend wrapper and connect to the test infrastructure

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx-mxnet#3]
ONNX has particular format of how to wrap backends in python and provide a uniform API. The benefit of having the unified API is that we can build tools that operate on several backends. In particular test infrastructure (both node level and model level) works via this API.

You can find the docs on the matter in [here](https://github.com/onnx/onnx/blob/master/docs/Implementing%20an%20ONNX%20backend.md) and [here](https://github.com/onnx/onnx/blob/master/docs/ONNX%20Backend%20Test.md)

It'd be really awesome if we could have the same wrapper for onnx-mxnet. It'd also make your testing procedure easier.

**Comment by Roshrini** [comment]
Thanks for pointing out the resources. Working on this.

**Comment by Roshrini** [comment]
Added the wrapper to connect to onnx test infra. #8
