### ISSUE TITLE
Update test_models.py

### ISSUE THREAD

**Issue by Roshrini** [onnx/onnx-mxnet#37]
Onnx has updated all the models to use data from .npz format to .pb format

For example: https://github.com/onnx/models/tree/master/squeezenet

Change test to use new data format.

**Comment by anirudhacharya** [comment]
We are now using the .pb files for all the local model tests like here - https://github.com/apache/incubator-mxnet/blob/master/tests/python-pytest/onnx/onnx_test.py#L153-L184

Squeezenet and a lot of other model tests which previously used to use .npz files are now being run using onnx_backend test.

Closing this issue, as it is fixed.
