### ISSUE TITLE
change pip dependence on mxnet

### ISSUE THREAD

**Issue by dwSun** [onnx/onnx-mxnet#4]
I am using mxnet-mkl, but when I try to install onnx_mxnet with pip, mxnet not using MKL also be installed as dependence.
Can you remove mxnet dependence or try to figure out which version the user has installed during installation?

**Comment by lupesko** [comment]
Thanks for the suggestion @dwSun .
Our plan is to merge onnx-mxnet into the mxnet code base pretty soon, at that point you will just get onnx capabilities within whatever mxnet package you use.
So we prefer to keep the easy user experience for mxnet users for now (i.e. having mxnet as a dependency of onnx-mxnet).
For now, you can manually install onnx-mxnet, uninstall mxnet and install mxnet-mkl - this will allow you to use mxnet-mkl
