### ISSUE TITLE
Problem printing summary of loaded onnx model

### ISSUE THREAD

**Issue by ThomasDelteil** [onnx/onnx-mxnet#43]
cross-referecing this issue in case it is a onnx-mxnet issue https://github.com/apache/incubator-mxnet/issues/10093
If the "no_bias":"False" is interpreted as truthy, it could explain some of the issues in reproducing results as well

**Comment by spidyDev** [comment]
Tested with using master branch of Mxnet and onnx-mxnet. Seems to work. onnx-mxnet is setting as `False`, might be mxnet issue fixed in master.

**Comment by ranman** [comment]
Fixed here: https://github.com/apache/incubator-mxnet/commit/f14b2ebcb5475b0cde205648d0b80e3378e3dbed

**Comment by spidyDev** [comment]
Thanks @ranman  . 
@ThomasDelteil  Closing this issue
