### ISSUE TITLE
Load ONNX model in Gluon

### ISSUE THREAD

**Issue by ThomasDelteil** [onnx/onnx-mxnet#44]
I am having some difficulties loading the ONNX model in Gluon.

```python
sym, params = onnx_mxnet.import_model(onnx_path)

symbol_block = gluon.nn.SymbolBlock(
    outputs=new_sym,
    inputs=mx.sym.var('input_0'))

```

However the only way to load params in a symbol block is from a file (`.load_params(filepath)`) rather than the params object given by onnx_mxnet. Any recommendations?

Ideally if there could be a `load_model_gluon()` on onnx_mxnet that would return a SymbolBlock that would be great.

**Comment by ThomasDelteil** [comment]
You can load the model in gluon like that:

```python
sym, params = onnx_mxnet.import_model(onnx_path)

net = gluon.nn.SymbolBlock(outputs=sym, inputs=mx.sym.var('input_0'))

net_params = net.collect_params()
for param in params:
    if param in net_params:
        net_params[param]._load_init(params[param], ctx=ctx)
```

**Comment by anirudhacharya** [comment]
Yes there is a plan to expose an API that will import onnx models to gluon directly.

**Comment by lupesko** [comment]
Can we provide an implementation that is similar to the function @ThomasDelteil implemented, as part of the work on MXNet 1.2 API?
@anirudhacharya @spidyDev

**Comment by anirudhacharya** [comment]
The implementation will not be a problem, but before it could be included in a release, it will have to be  tested with models from the onnx model zoo and for other various corner cases. 

It will have to pass all the current tests that we have for the onnx-mxnet API.

**Comment by lupesko** [comment]
This is part of the plan for MXNet ONNX contrib API, see [here](https://cwiki.apache.org/confluence/display/MXNET/ONNX-MXNet+API+Design)

Closing.
