### ISSUE TITLE
Operator "Constant" not implemented

### ISSUE THREAD

**Issue by mosessoh** [onnx/onnx-mxnet#9]
Hi guys, I'm converting a onnx model with the U-Net architecture to mxnet. 

```
~/anaconda3/envs/pytorch_gpu/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/import_onnx.py in _convert_operator(op_name, attrs, identity_list, convert_map)
     49         op_name, attrs = convert_map[op_name](attrs)
     50     else:
---> 51         raise NotImplementedError("Operator {} not implemented.".format(op_name))
     52     op = getattr(mx.sym, op_name, None)
     53     if not op:

NotImplementedError: Operator Constant not implemented.
```

I noticed Constant is one of the generators from [this link](https://github.com/dmlc/nnvm/blob/3da53e46db57c438b05fbebe8aa332ee8c5994d1/python/nnvm/frontend/onnx.py). Is there any way I can get around this, or help implement something? I'm totally new to onnx, but if you guys can point me in the right direction, I could give it a try.

**Comment by Roshrini** [comment]
Hi, Thanks for trying it out. [onnx constant](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant) operator seems similar to [mxnet's identity](http://mxnet.incubator.apache.org/api/python/symbol/symbol.html#mxnet.symbol.identity) operator.
You can try to add this operator conversion [here](https://github.com/onnx/onnx-mxnet/blob/master/onnx_mxnet/import_helper.py).

**Comment by mosessoh** [comment]
hey sorry was caught up with meeting the submission deadlines for my class tomorrow!

alright, so I tried the mxnet's identity operator and it worked (got passed the previous error), but I ran into additional bugs. I also found some other typos in the code, so let me submit a PR.

you can get my model from my [project github repo](https://github.com/mosessoh/iconcolor) — clone it and run the `fetch_model.py` script.

**Comment by mosessoh** [comment]
I'm finding that I should change 
```
'LeakyRelu'     : AttrCvt('LeakyReLU', {'alpha', 'slope'}),
```
to 
```
'LeakyRelu'     : AttrCvt('LeakyReLU', {'alpha': 'slope'}),
```

otherwise I run into this error.

```
Conv
<function Convolution at 0x7fc9160b6620>
BatchNormalization
<function BatchNorm at 0x7fc9160b6488>
LeakyRelu
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-710a77083a59> in <module>()
----> 1 sym, params = onnx_mxnet.import_model('outline2yellow_gan.onnx')

~/anaconda3/envs/pytorch_gpu/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/__init__.py in import_model(model_file)
     32     # loads model file and returns ONNX protobuf object
     33     model_proto = onnx.load(model_file)
---> 34     sym, params = graph.from_onnx(model_proto.graph)
     35     return sym, params

~/anaconda3/envs/pytorch_gpu/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/import_onnx.py in from_onnx(self, graph)
    113             attr = self._parse_attr(node.attribute)
    114             print(op_name)
--> 115             new_op, new_attr = _convert_operator(op_name, attr)
    116             print(new_op)
    117             inputs = [self._nodes[self._renames.get(i, i)] for i in node.input]

~/anaconda3/envs/pytorch_gpu/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/import_onnx.py in _convert_operator(op_name, attrs, identity_list, convert_map)
     47         pass
     48     elif op_name in convert_map:
---> 49         op_name, attrs = convert_map[op_name](attrs)
     50     else:
     51         raise NotImplementedError("Operator {} not implemented.".format(op_name))

~/anaconda3/envs/pytorch_gpu/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/common.py in __call__(self, attrs)
     99                 pass
    100             elif k in self._transforms:
--> 101                 new_name, defaults, transform = self._parse_default(self._transforms[k])
    102                 if defaults is None:
    103                     new_attr = self._required_attr(attrs, k)

TypeError: 'set' object is not subscriptable
```

Should I be creating a separate issue to document this or just include the revision in my PR?

**Comment by Roshrini** [comment]
Thanks for fixing it. Closing this issue.

**Comment by lupesko** [comment]
@mosessoh thanks for your contribution!
Can you share your imported MXNet model by contributing it to [MXNet model zoo](https://mxnet.incubator.apache.org/model_zoo/)?

**Comment by mosessoh** [comment]
Yes I'll work on that! Sorry for the delay in getting back to you all - it's the festive season.
